baseURL = "https://b.sattellite.me/"
languageCode = "ru-RU"
title = "Blogggg"
theme="blogggg"

[permalinks]
posts = "/:year/:month/:filename"

[taxonomies]
tag = "tags"

[params]
mainSections = ["posts"]
author = "Alexander Groshev"
email = "blog@sattellite.me"
github = "sattellite"
telegram = "sattellite"
twitter = "_sattellite"
description = "Yet another blog"

[markup.goldmark.renderer]
unsafe= true
